const STARTING_TIME_IN_MINUTES_SINCE_MIDNIGHT = 27.0;
const END_TIME_IN_MINUTES_SINCE_MIDNIGHT= 141;
const TIMESCALE = 3;

export {STARTING_TIME_IN_MINUTES_SINCE_MIDNIGHT, END_TIME_IN_MINUTES_SINCE_MIDNIGHT, TIMESCALE}